### PR TITLE
Updated and working with branch 3071 revision 1640

### PR DESCRIPTION
**Pull request by alkemir**
Hi Czarek,

I got this working on windows (32-bits). I am just learning about cgo,
so this might be ready for general usage,
but I rather leave that decision to the expert. Keep up the good work!

### CODE REVIEW

**Comment by alkemir** [comment]
Just tested windows 64 bits and it works too.

**Comment by cztomczak** [comment]
Did the "Getting started" instructions change? If so README.md should be updated.

When updating the include/ directory, where did you get the files from? From the binaries from Spotify or from CEF git repository? (the latter is correct).

I can't see differences in the src/cef/cef.go file, because you have replaced all spaces with tabs in that file. If updating spaces to tabs then this should become a separate issue/pr and be applied for all Go files in the project.

**Comment by alkemir** [comment]
I will check if the same instructions apply.

I got the files from Spotify; I will update with the CEF git repository. Why is there a difference?

I will submit this PR with spaces.

**Comment by cztomczak** [comment]
The include/ directory from Spotify does not include Linux/Mac platforms specific files.

**Comment by cztomczak** [comment]
What Go version of the lang are you testing with? You should update the Compatibility section in README as well.

**Comment by cztomczak** [comment]
The changes in CEF capi files (the handlers/ directory) have errors. For example add_ref  should return void now. Also initialize_cef_base should be renamed to initialize_cef_base_refcounted. Possibly other changes required as well. It's best to use header files from the cefcapi project which was updated recently to work with CEF branch 3029: https://github.com/cztomczak/cefcapi

**Comment by alkemir** [comment]
I have everything almost ready, except I am having issues with
g_life_span_handler . I am not familiar to cgo, is there a way to export
this to C?

**Comment by alkemir** [comment]
Nevermind, I figured it out. Trying again.

**Comment by cztomczak** [comment]
It would be best if you created a separate branch in your fork for these set of changes. This will not get merged immediately, it will have to wait until all platforms are tested, however it is stil useful for other users that want to get latest CEF working.

**Comment by cztomczak** [comment]
Just a note for the future - it's best to update CEF header files in a separate commit for easier reviewing for all the other files.

**Comment by alkemir** [comment]
Czarek,

thank you so much for your feedback. I will follow it.

Hopefully, I can get people from the office to test this on Mac and Linux during the week.

**Pull request closed without merging**
